apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: ds-app
    meta.helm.sh/release-namespace: default
spec:
  selector:
    app: backend
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.ports.container }}
  type: {{ .Values.backend.service.type }}
