apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
          ports:
            - containerPort: {{ .Values.backend.ports.container }}
          env:
            - name: SPRING_DATASOURCE_URL
              value: "{{ .Values.backend.database.url }}"
            - name: SPRING_DATASOURCE_USERNAME
              value: "{{ .Values.backend.database.username }}"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "{{ .Values.backend.database.password }}"
          resources:
            requests:
              cpu: {{ .Values.backend.resources.requests.cpu }}
            limits:
              cpu: {{ .Values.backend.resources.limits.cpu }}


