apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-first-helm-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Mariamatambedou/kubernetes.git' 
    targetRevision: main          
    path: my-first-helm           
    helm:
      valueFiles:
        - values.yaml            
      releaseName: my-first-app   
  destination:
    server: https://kubernetes.default.svc  
    namespace: default            
  syncPolicy:
    automated:
      prune: true                 
      selfHeal: true        
