apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard  # Assurez-vous que cette StorageClass correspond à celle du PVC
  hostPath:
    path: "/mnt/data/mysql"  # Dossier sur le nœud pour le stockage
  persistentVolumeReclaimPolicy: Delete  # Pour le supprimer automatiquement si nécessaire

