name: Deploy to Minikube

on:
  push:
    branches:
      - main  # Déclenche le workflow sur push vers main

jobs:
  deploy:
    runs-on: self-hosted  # Spécifie que le workflow s'exécute sur un runner auto-hébergé
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          lfs: true
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Set up kubectl
        run: |
          # Vérifiez si kubectl est configuré pour Minikube
          kubectl get nodes
      - name: Create Persistent Volume for MySQL
        run: |
          kubectl apply -f k8s/mysql-pv.yaml 

      - name: Deploy MySQL
        run: |
          kubectl apply -f k8s/mysql-deployment.yaml

      - name: Deploy Backend
        run: |
          kubectl apply -f k8s/backend-deployment.yaml

      - name: Deploy Frontend
        run: |
          kubectl apply -f k8s/frontend-deployment.yaml

      - name: Deploy Ingress
        run: |
          kubectl apply -f k8s/ingress.yaml

      - name: Configure Autoscaling for Backend
        run: kubectl apply -f k8s/autoscale-backend.yaml
